#!/sbin/sh

# ---------------------------
# Set date + time, and fix epoch issues in OrangeFox recovery
# Useful in OrangeFox recovery when the device's RTC is misbehaving
#
# By DarthJabba9
#
# Usage: setdate "2021-04-27-16:31"
# 
# date format: date +%Y%m%d%H%M -s 202104271715
# Copyright (C) 2018-2021 The OrangeFox Recovery Project
# 28 April 2021
# -------------------------

bb=$(which busybox)
if [ -n "$bb" ]; then
   date_cmd="$bb date"
else
   date_cmd="date"
fi

# copy the ROM version to /sdcard/Fox/
if [ ! -f /sdcard/Fox/fox_fix_date ]; then 
   mkdir -p /sdcard/Fox/
   cp -a /FFiles/fox_fix_date /sdcard/Fox/
   chmod 0755 /sdcard/Fox/fox_fix_date
fi

# process the arguments
if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo "Usage =  $0 YYYY-mm-dd-HH:MM"
   echo "Example: $0 2021-04-27-16:31"
   exit 0
fi

# check/save the time drift values
save_drift() {
	[ ! -d /persist ] && return

	local M=$(cat /proc/mounts | grep "/persist")
	[ -z "$M" ] && mount /persist > /dev/null 2>&1

	local epoch_cfg=/persist/.fox_epoch_drift.cfg
	local now=$($date_cmd +%s)
	local epoch=$(cat /sys/class/rtc/rtc0/since_epoch)
	local drift=$(expr $now - $epoch)

	# allow 5 minutes drift
	if [ $drift -gt 600 ]; then
	    echo -n "$drift" > $epoch_cfg
	fi

	[ -z "$M" ] && umount /persist > /dev/null 2>&1
	echo "Drift ($now minus $epoch)=$drift"
}

# configure
DateStr="+%Y%m%d%H%M"
Value="$1"
Value=$(echo "$1" | tr -d "-")  # remove "-"
Value=$(echo "$Value" | tr -d ":") # remove ":"
Value=$(echo "$Value" | tr -d " ") # remove space

# change the date
set_arg=""
if [ -n "$bb" ]; then
   DateStr=$DateStr" -s"
else
   set_arg="set"
fi

CMD="$date_cmd $DateStr $Value $set_arg"
echo "- Running command: $CMD"
$CMD

# save it
save_drift

# return
exit 0;

