#!/sbin/sh

# ---------------------------
# Set date + time in OrangeFox recovery
#
# By DarthJabba9
#
# Usage: setdate "2021-04-28-16:31"
# 
# date format: date +%Y%m%d%H%M -s 202104271715
# Copyright (C) 2018-2021 The OrangeFox Recovery Project
# 28 April 2021
# -------------------------

# process the arguments
if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   echo "Usage =  $0 YYYY-mm-dd-HH:MM"
   echo "Example: $0 2021-04-27-16:31"
   exit
fi

bb=$(which busybox)
if [ -n "$bb" ]; then
   date_cmd="$bb date"
else
   date_cmd="date"
fi

# configure
DateStr="+%Y%m%d%H%M"
Value="$1"
Value=$(echo "$1" | tr -d "-")  # remove "-"
Value=$(echo "$Value" | tr -d ":") # remove ":"
Value=$(echo "$Value" | tr -d " ") # remove space

# change the date
set_arg=""
if [ -n "$bb" ]; then
   DateStr=$DateStr" -s"
else
   set_arg="set"
fi

CMD="$date_cmd $DateStr $Value $set_arg"
echo "- Running command: $CMD"
$CMD
exit 0;
