#!/sbin/sh
#
# - Custom script for OrangeFox Recovery
# - Copyright (C) 2019-2020 OrangeFox Recovery Project
# - Author: DarthJabba9
# - Date:   27 July 2019
# - "fox_pre_flash" script, for lavender/violet/perseus - to mount system on system_root
# - before flashing zips (apart from ROMs)
#
#

is_mounted() {
  [ -z "$1" ] && { echo "0"; return; }
  grep -q " `readlink -f $1` " /proc/mounts 2>/dev/null
  [ "$?" = "1" ] && echo "0" || echo "1"
}

do_mount_system() {
local LOGF=/tmp/recovery.log
local F=$(getprop "ro.build.system_root_image" 2>/dev/null)
   echo "DEBUG: OrangeFox: mounting system on system_root..." >> $LOGF
   [ "$F" != "true" ] && {
      return
   }

   F=$(is_mounted "/system")
   [ "$F" = "1" ] && {
      return
   }
   
   mount -o rw /dev/block/bootdevice/by-name/system /system > /dev/null 2>&1
   mount --move /system /system_root > /dev/null 2>&1
   mount -o bind /system_root/system /system  > /dev/null 2>&1
   echo "DEBUG: OrangeFox: finished mounting system on system_root" >> $LOGF
}

#
do_mount_system
#
