#!/sbin/sh
#
# nano: set up and run nano from recovery/terminal
# osm0sis @ xda-developers
# DarthJabba9  @ xda-developers
#

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage = $0 [--term <terminal>] [arguments]"
    F=/FFiles/nano/terminals.txt
    [ -e $F ] && cat $F
    exit 0
fi

if [ "$1" == "--term" ]; then
   term=$2
   shift 2
else
   term=pcansi
fi

clear;

# *************************************
NANO_DIR=/FFiles/nano
nano_bin=$NANO_DIR/bin/nano.bin
# *************************************
export TERMINFO=$NANO_DIR/terminfo 
export TERM=$term 

if [ -e $nano_bin ] && [ ! -x $nano_bin ]; then
   chmod 0755 $nano_bin
fi

$nano_bin "$@";
#
